[package]
name = "jt51-plugin"
version = "0.1.0"
authors = ["Hans Baier <hansfbaier@gmail.com>"]
edition = "2018"

[dependencies]
vst = { git = "https://github.com/rustaudio/vst-rs" }
midly = "0.5.2"

[lib]
name = "jt51_plugin"
crate-type = ["cdylib"]
